Revert "Automatically create data-viewers and data-editors groups"
This reverts commit 10567a7ff964a8398324be29000828c1b84a99db.

On `pulumi up` we get the following error that i can't seem to figure
out

    error: 1 error occurred:
        * Error creating Group: googleapi: Error 403: Your application
          is authenticating by using local Application Default Credenti
          als. The cloudidentity.googleapis.com API requires a quota
          project, which is not set by default. To learn how to set your
          quota proj ect, see
          https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds
          .

    Details:
    [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/764086051850",
          "service": "cloudidentity.googleapis.com"
        },
        "reason": "SERVICE_DISABLED"
      }
    ]